//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favico_ico {
            get {
                object obj = ResourceManager.GetObject("favico.ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaksWorks™ Presents a Chatroom Studio™ Chat tTo Podcast Audio Transcription.
        /// </summary>
        internal static string PresentationWaksWorksPresents {
            get {
                return ResourceManager.GetString("PresentationWaksWorksPresents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp Chat With CO88.txt.
        /// </summary>
        internal static string SampleFileName {
            get {
                return ResourceManager.GetString("SampleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23/04/2023, 20:53 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
        ///23/04/2023, 20:53 - Wole Solanke created group &quot;Product development&quot;
        ///23/04/2023, 20:53 - Wole Solanke added you
        ///23/04/2023, 20:53 - +27 78 419 6615: Holla!
        ///23/04/2023, 20:53 - Wole Solanke changed the subject from &quot;Product development&quot; to &quot;KaraSell&quot;
        ///23/04/2023, 20:54 - Wole Solanke: Got ya
        ///23/04/2023, 20:59 - W2W3: Hey!
        ///23/04/2023, 21:03 - W2W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInput_txt {
            get {
                return ResourceManager.GetString("TestInput.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23/04/2023, 20:53 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
        ///23/04/2023, 20:53 - Wole Solanke created group &quot;Product development&quot;
        ///23/04/2023, 20:53 - Wole Solanke added you
        ///23/04/2023, 20:53 - +27 78 419 6615: Holla!
        ///23/04/2023, 20:53 - Wole Solanke changed the subject from &quot;Product development&quot; to &quot;KaraSell&quot;
        ///23/04/2023, 20:54 - Wole Solanke: Got ya
        ///23/04/2023, 20:59 - W2W3: Hey!
        ///23/04/2023, 21:03 - W2W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhatsApp_Chat_with_KaraSell {
            get {
                return ResourceManager.GetString("WhatsApp Chat with KaraSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17/05/2023, 01:12 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
        ///17/05/2023, 01:13 - Chatroom Studios: It&apos;s marc
        ///17/05/2023, 01:13 - Chatroom Studios: And this is my business number too
        ///17/05/2023, 01:14 - Olu Eko: Alright cool
        ///17/05/2023, 01:15 - Chatroom Studios: What&apos;s your email?
        ///17/05/2023, 01:15 - Olu Eko: Oyedun2010@gmail.com
        ///17/05/2023, 01:16 - Olu Eko: How many bedroom for the house? I mean for the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhatsApp_Chat_with_Olu_Eko {
            get {
                return ResourceManager.GetString("WhatsApp Chat with Olu Eko", resourceCulture);
            }
        }
    }
}
